version: 2.1

jobs:
  test:
    docker:
      - image: okitan/kaniko-circleci:latest
    steps:
      - run: /kaniko/executor version

workflows:
  test:
    jobs:
      - test
  cron:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
